spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v_service_manage
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: yravindu18@gmail.com
    password: jzne otip raom hfmi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
